config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do
    resources :comments
    resources :attachements
    resources :likes
  end 

  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete

  root to: 'posts#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2>Login</h2>
      </div>
      <div class="modal-body">
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
        <div><%= f.label :email %><br />
        <%= f.email_field :email, :autofocus => true %></div>

        <div><%= f.label :password %><br />
        <%= f.password_field :password %></div>

        <% if devise_mapping.rememberable? -%>
          <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
        <% end -%>
        <div><%= f.submit "Sign in", :class => 'btn btn-small btn-success' %></div>
        <% end %>
      </div>
      <div class="modal-footer">
      <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>  
</div>

app/views/welcome/_sign_up_modal.html.erb
<div class="modal fade" id="sign_up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2>Sign Up</h2>
      </div>

      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :multipart => true }) do |f| %>
        <%= devise_error_messages! %>

        <div><%= f.label :email %><br />
        <%= f.email_field :email, :autofocus => true %></div>
         
         <p><%= f.label :username %><br />
        <%= f.text_field :username %></p>

        <div><%= f.label :password %><br />
        <%= f.password_field :password %></div>

        <div><%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %></div>
        <br />

<!--         Add an Avatar:
        <#%= f.fields_for :image do |form| %>
         <#%= form.file_field :image, as: :file %>
        <#% end %> -->

        <div><%= f.submit "Sign up", :class => 'btn btn-small btn-success' %></div>
      </div>
      <div class="modal-footer">
      <%= render "devise/shared/links" %>
      </div>
    <% end %>
   </div>
  </div>  
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>