config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do
    resources :comments
    resources :attachements
    resources :likes
  end 

  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete

  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
  has_many :likes, dependent: :destroy
	belongs_to :user
  has_many :attachements, as: :attachable, dependent: :destroy
  accepts_nested_attributes_for :attachements, :allow_destroy => true

	has_attached_file :image, styles: { thumb: "64x64", med: "100x100", large: "200x200" }, 
		default_url: ":rails_root/public/system/app/images/:style/missing.png",
        :url  => "/assets/images/posts/:basename.:extension",
        :path => ":rails_root/public/assets/images/posts/:basename.:extension"

  	validates_attachment_size :image, :less_than => 5.megabytes
  	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

  	validates :title, presence: true,
                    length: { minimum: 5 }
    acts_as_taggable

    scope :sort_by_newest, -> { order(created_at: :desc) }
    scope :username, -> { User.find(user_id) }


  def liked?(user)
    if !user.nil?
      if likes.loaded?
        !!likes.find { |l| l.user_id == user.id }
      else
        likes.where(user_id: user.id).exists?
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :get_post, only: [:edit, :update, :destroy]
  before_action :same_user , only: [:edit,:update,:destroy]


  def index
    @posts = Post.preload(:attachements, :user, :likes)
    if params[:sort_by] == 'date_newest'
      @posts = @posts.sort_by_newest
    end
    if params[:sort_by] == 'date_oldest'
      @posts = @posts.order(created_at: :asc)
    end
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    end
    if params[:sort_by] == 'most_comments'
      @posts = @posts.joins(:comments).group("posts.id").order("count(comments.id) desc")
    end
    if params[:sort_by] == 'most_likes'
      @posts = @posts.joins(:likes).group("posts.id").order("count(likes.id) desc")
    end
    if params[:sort_by] == 'most_views'
      @posts = @posts.order(views: :desc)
    end
  end

	def show
    	@post = Post.find(params[:id])
      @post.increment(:views, 1)
      @post.save
  end

	def new
		@post = Post.new
    @post.views=0
    @post.save
	end

	def edit
		@post = current_user.posts.find(params[:id])
    
    
    #current_user validation 
	end

	def create
	  @post = Post.new(post_params)
    @post.user_id = current_user.id
    	if @post.save 
        if params[:attachments].present?
          params[:attachments]['image'].each do |a|
            @attachement = @post.attachements.create!(:image => a)
          end
        end
        @post.likes_count = 0;
        @post.comments_count = 0;
      	redirect_to posts_path
  	end
  end	


  def update
  	@post = current_user.posts.find(params[:id])

  	if @post.update(post_params)
        if params[:attachments].present?
          params[:attachments]['image'].each do |a|
            @attachement = @post.attachements.create!(:image => a)
          end
        end


  		redirect_to post_path(@post)
  	end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
 
    redirect_to posts_path
  end


	   private
       def get_post
        @post = Post.find(params[:id])
      end

  	private
  		def post_params
    		params.require(:post).permit(:title, :description, :tag_list, :lat, :lng, :loc_name, :image, 
          attachements_attributes: [:id, :post_id,:_destroy, :image])
  		end



  def same_user
    @post = Post.find(params[:id])
    if current_user != @post.user
        flash[:danger] = "Your are not allowed"
        redirect_to root_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
    # def nav_link(text, link)
    #     recognized = Rails.application.routes.recognize_path(link)
    #     if recognized[:controller] == params[:controller] && recognized[:action] == params[:action]
    #         content_tag(:li, :class => "sort-active") do
    #             link_to( text, link)
    #         end
    #     else
    #         content_tag(:li) do
    #             link_to( text, link)
    #         end
    #     end
    # end
end

app/views/posts/_comments.html.erb
<% id = "post-comments-#{post.id}" %>
<div class="modal fade" id="<%= id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">


  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2>Comments</h2>
      </div>
      <div class="modal-body">
        <% post.comments.each do |f| %>
          <div class="panel panel-primary">
              <div class="panel-body"> 
                  <%= f.body %>
              </div>
              <div class="panel-footer">
                  <small>
                   Posted by: <%= f.user.username %>
                  </small>
              </div>
            </div>
          <% end %>
          <h2>Add a comment:</h2>
          <%= form_for([post, post.comments.build]) do |t| %>
            <p>
              <%= t.text_area :body, style: "min-width: 100%", rows: "5"%>
            </p>
    			<div class="modal-footer">
              <p>
                <%= t.button 'Save', :class => 'btn btn-primary' %>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </p>
            <% end %>
    			</div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_display.erb
<% id = "post-display-#{post.id}" %>
<div class="modal fade bd-example-modal-lg" id="<%= id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="card-block">


        <li><h4 class="card-title"><%= post.title %></h4></li>

        <div class="panel-body flex-text">
          <li><%= post.description %></li>
        </div>

        <div class="panel-body">
          <li class="">Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></li>
          <li>Location: <%= post.loc_name %></li>
          <!--li>Latitude: <%#= post.lat %>, Longitude: <%#= post.lng %></li>-->
        </div>
      </div>
        <% post.attachements.each do |a| %>
          <%= image_tag a.image.url(:large), class: "flex-row modal-pictures" %>
        <% end %>

      <div class="panel-body">

          <ul class="nav navbar-nav">
                <% if logged_in? && current_user == post.user %>           
                  <%= render 'modal', post: post %>
                  <li> 
                    <%= button_to post, method: :delete, remote: true, class: "btn btn-primary btn-sm" do %>
                      Delete Post
                    <% end %>
                  </li>
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-dismiss="" data-target="#edit-post-<%= post.id %>">
                      Edit Post
                    </button>    
                  </li>
                <% end %>
           </ul>
        </div>
      </div>
  </div>
</div>

app/views/posts/_images_upload.erb
Add Mutiple Images:
<%= post.fields_for :attachement do |attachements_form| %>
 <%= attachements_form.file_field :attachement, :multiple => true, name: "attachments[image][]" %>
<% end %>
<br />

app/views/posts/_modal.html.erb
<% id = post.new_record? ? 'new-post' : "edit-post-#{post.id}" %>
<div class="modal fade" id="<%= id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">


  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= render 'post_form', :pass_post => post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_form.html.erb
<div class="post post-show">
	<% if @post.nil? %>
		<% @post = Post.new %>
	<% end %>
	<%= form_for @post, id: "postform", :html => { :multipart => true } do |f| %>
		
		<h2 class="card-title">
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</h2>
	<div class="panel-body flex-text">
			<%= f.label :description %><br>
			<%= f.text_area :description, style: "min-width: 100%", rows: "5" %> 
		
		<p>
			<%= f.label :tag_list, "Tags (separated by commas)" %><br />
			<%= f.text_field :tag_list, size: '40x8' %>
		</p>

		<%= render 'images_upload', :post => f %>  

		<%= f.fields_for :attachements do |fa| %>
			<div class="modal-pictures">
				Change Image:<%= fa.file_field :image %>
				Delete Image <%= fa.check_box "_destroy" %><br />
				<%= image_tag fa.object.image.url(:small), class: "img-thumbnail" %>
				<br />
			</div>
		<% end %>

		<p><br />
			Add a Location:
			<%= f.text_field :loc_name, placeholder: "Location", id: "autocomplete", onFocus: "geolocate()", type: "text", size: '40x8' %><br />
			<%=f.hidden_field :lng, id: "lng" %>
	    	<%=f.hidden_field :lat, id: "lat" %>
	    	<%=f.hidden_field :loc_name, id: "formatted_address" %>
		</p>
	</div>
		<!--div class="map_canvas"></div-->


		<div class="modal-footer">
			<%= f.button 'Save', id: "save-button", :class => 'btn btn-primary' %>
			<%= link_to 'Back', posts_path, type: "button", class: "btn btn-primary btn-default" %>
		</div>
	<% end %>
</div>


    <script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        document.getElementById('lat').value = place.geometry.location.lat();
        document.getElementById('lng').value = place.geometry.location.lng();
        document.getElementById('formatted_address').value = place.formatted_address;

      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-CClVVnN2RnG6ICiyr-Vh_qLgQpbYhU0&libraries=places&callback=initAutocomplete"
        async defer></script>
	

app/views/posts/edit.html.erb
<%= render 'post_form', post: @post %>
 

app/views/posts/index.html.erb
<!-- Post Body-->
<section class="post-nav">
  <div class="sort-bar" >
  <ul id="post-tabs" class="nav nav-tabs">
      <li class=""><%= link_to( 'Most Recent', 'posts?sort_by=date_newest') %></li>
      <li class=""><%= link_to('Oldest', 'posts?sort_by=date_oldest') %></li>
      <li class=""><%= link_to('Most Popular', 'posts?sort_by=most_likes') %></li>
      <li class=""><%= link_to('Most Viewed', 'posts?sort_by=most_views') %></li>
      <li class=""><%= link_to('Most Comments', 'posts?sort_by=most_comments') %></li>
  </ul>
</section>


<ul class="post card-deck-wrapper">
  <div class="flex-row row">
	<% @posts.each do |f| %>


      <div class="col-xs-6 col-sm-4 col-lg-3">
        <%= link_to(post_path(f), class: "no-style") do %>

      		<li> <%#= f.created_at.strftime('%D') %></li>
      		<div class="panel-primary" id="post-container">

            <div class="flex-row">
              <li>
                <%= image_tag f.attachements.first.image.url(:large), class: "post-img" %>
              </li>
            </div>
            <div class="card-block">
              <li><h4 class="card-title"><%= f.title %></h4></li>
                <div class="panel-body flex-text">
                  <li><%#= f.description %><%=h truncate(f.description, :length => 80) %></li>
                  <li>
                    <%= f.liked?(current_user) %>   
                    <% if f.liked?(current_user) %>
                     <input type="button" value="よっくない！" class="btn btn-secondary like-button" data-target="<%= f.id %>" id="like_button" /> 
                    <% else %>
                      <input type="button" value="いいね！" class="btn btn-primary like-button" data-target="<%= f.id %>" id="like_button" /> 
                    <% end %>
                  <br />     
                    <% if f.views.present?  %>    
                      <%= f.views %>
                      <%=image_tag("views_icon.png", class: "post-icon")%>
                    <% end %>
                    <% if f.comments.count > 0  %>  
                      <%= f.comments.count %>
                      <%=image_tag("comments_icon.png", class: "post-icon")%>
                    <% end %>  
                    <% if f.likes.count > 0 %>    
                      <%= f.likes.count %>
                      <%=image_tag("heart_icon.png", class: "post-icon")%>
                    <% end %>
                    <% if f.attachements.count > 0  %>  
                      <%= f.attachements.count %>
                      <%=image_tag("picture_icon.png", class: "post-icon")%>
                    <% end %>  
                  
                  </li> 
              
                </div>

            </div>


    		  	</div>
            <% end %>
            <small>Posted by <%= f.user.username %></small><br />
		  </div>

  	<% end %>
    </div>
</ul>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <script type="text/javascript">
    $('.like-button').on('click', function(event){
          event.preventDefault();

          postId = $(this).attr("data-target");
          console.log("Clicked like: ", postId, "<%= like_path() %>", "<%= form_authenticity_token %>", this.value);
          
          if (this.value == "いいね！") {
            this.value = "よっくない";
            this.className = "btn btn-secondary like-button";
            $.post('/like', {
                post_id: postId, 
                authenticity_token: "<%= form_authenticity_token %>"
              }).done(function(){console.log('created');}).fail(function(){console.log('failed create');});
            /*$.ajax({
              type: "POST",
              //url: "<%= like_path() %>",
              url: "/like",
              data: {
                post_id: postId, 
                authenticity_token: "<%= form_authenticity_token %>"
              },
              success: function(){
                console.log("yay! Success")
              },
              error:function(data){
                this.value = "いいね！"
                this.className = "btn btn-primary like-button";
                debugger;
              },
              dataType: "json"

            });*/
          }else {
            this.value = "いいね！"
            this.className = "btn btn-primary like-button";
            $.post('/unlike', {
                post_id: postId, 
                "_method":"delete",
                authenticity_token: "<%= form_authenticity_token %>"
              }).done(function(){console.log('deleted');}).fail(function(){console.log('failed delete');});
            /*$.ajax({
              type: "POST",
              url: "<%= unlike_path() %>",
              data: {
                post_id: postId, 
                "_method":"delete", 
                authenticity_token: "<%= form_authenticity_token %>"
              },
              success: function(){
                console.log("yay! Deleted")
              },
              error:function(data){
                this.value = "よっくない";
                this.className = "btn btn-secondary like-button";
                debugger;
              },
              dataType: "json"

            });*/
          }
    });
  </script>

<style>
/* Extra Media Query Below for Retina Iphones and Smaller */
@media only screen and (max-width : 480px){
  .flex-row > [class*='col-'] {
      width: 100%;
  }
  .flex-row  {
    padding-left: 0px;
    padding-right: 0px;
  }
}
</style>

app/views/posts/like.js.erb
$('div#<%= dom_id(@post) %>').html('<%= j render partial: "button", locals: {post: @post} %>');

app/views/posts/new.html.erb
 <%= render 'post_form', post: @post %>
 

app/views/posts/show.html.erb
<div class="post post-show">
  <div class="col-xs-14 col-md-10">
    <li><h2 class="post-title">&nbsp;&nbsp;<%= @post.title %></h2></li>
      <div class="panel-body flex-text">
        <li><%= @post.description %></li>
      </div>

      <div class="panel-body">
        <li class="">Tags: <%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></li>
        <li>Location: <%= @post.loc_name %></li>
        <li>
          <% if @post.views.present?  %>    
            <%= @post.views %>
            <%=image_tag("views_icon.png", class: "post-icon")%>
          <% end %>
          <% if @post.comments.count > 0  %>  
            <%= @post.comments.count %>
            <%=image_tag("comments_icon.png", class: "post-icon")%>
          <% end %>  
          <% if @post.likes.count > 0  %>  
            <%= @post.likes.count %>
            <%=image_tag("heart_icon.png", class: "post-icon")%>
          <% end %>
        </li>

        <!--li>Latitude: <%#= post.lat %>, Longitude: <%#= post.lng %></li>-->
      </div>
        <% @post.attachements.each do |a| %>
          <%= image_tag a.image.url(:large), class: "flex-row post-show-pictures img-thumbnail" %>
        <% end %>
      <div class="panel-body">
        <ul class="list-inline">
          <% if logged_in? && current_user == @post.user %>           
            <li> 
              <%= button_to @post, method: :delete, remote: true, class: "btn btn-primary btn-default" do %>
                Delete Post
              <% end %>
            </li>
            <li>
              <%= link_to 'Edit Post', edit_post_path(@post), type: "button", class: "btn btn-primary btn-default post-button" %>
            </li>
          <% end %>
          <li>
            <%= link_to 'Back', posts_path, type: "button", class: "btn btn-primary btn-default" %>
          </li>
          <li>
            <%= div_for @post do %>
              <%= render partial: "likes/button", locals: { post: @post } %>
            <% end %>  
          </li>
        </ul>
      </div>

      <h3 class="card-title">Comments</h3>
      <div class="panel-body flex-text">
      <div class="container">
        <% @post.comments.each do |f| %>
          <div class="row">
          <div class="col-sm-1">
            <div class="thumbnail">
               <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
              <!-- Pictures go here -->

          </div><!-- /thumbnail -->
          </div><!-- /col-sm-1 -->
          <div class="col-sm-7">
            <div class="panel panel-default">
              <div class="panel-heading">
                <%= f.user.username %> commented <%= distance_of_time_in_words(DateTime.now, f.created_at) %>  ago
              </div>
              <div class="panel-body">
                  <% if f.user == @post.user %>
                    <div class="author-comment">
                      <i>Author Comment</i>
                    </div>
                    <br />
                  <% end %>
                    <%= f.body %>
              </div><!-- /panel-body -->
            </div><!-- /panel panel-default -->
          </div>  <!-- /col-sm-9 -->   
          <div class="col-sm-3">
            <% if logged_in? && current_user == f.user %>   
              <%= button_to [@post, f], method: :delete, remote: true, class: "btn btn-primary btn-sm" do %>
                Delete Comment
              <% end %>
            <%end%>
            </div>
        </div>

        <% end %>
        <div class="col-sm-10">
          <h3>Add a comment:</h3>
          <%= form_for([@post, @post.comments.build]) do |t| %>
            <p>
              <%= t.text_area :body, style: "min-width: 100%", rows: "5"%>
            </p>
          <div class="modal-footer">
              <p>
                <%= t.button 'Save Comment', :class => 'btn btn-primary post-button' %>
                <%= link_to 'Back', posts_path, type: "button", class: "btn btn-primary btn-default" %>
              </p>
          </div>
          <% end %>
        </div>
      </div>    
  </div>          
</div>     

app/views/posts/unlike.js.erb
$('div#<%= dom_id(@post) %>').html('<%= j render partial: "button", locals: {post: @post} %>');