config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do
    resources :comments
    resources :attachements
    resources :likes
  end 

  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete

  root to: 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Everything Japan
    <% end %>
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "flatly" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css?family=Calligraffitti|Lora|Prociono|Proza+Libre" rel="stylesheet">
  <link rel="shortcut icon" href=":rails_root/public/assets/images/favicon.ico" type="image/x-icon">
  <link rel="icon" href=":rails_root/public/assets/images/favicon.ico" type="image/x-icon">
  </head>
<body>

<% if user_signed_in? %>
  <%#= render 'modal', post: Post.new %>
<% else %>
  <%= render "welcome/login_modal" %>                 
  <%= render "welcome/sign_up_modal" %> 
<% end %>



  <%= stylesheet_link_tag "posts" %>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>

  <%= yield :top_content %>

  <!-- Navigation Section -->

      <nav class="navbar navbar-default navbar-fixed-top" id="nav-bar">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Everything Japan', posts_path, class: "navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to 'Home', posts_path %></li>
              <!--<li><a href="#about">Anime</a></li>
              <li><a href="#contact">Video Games</a></li>-->
              <li class="dropdown">
              <% if user_signed_in? %>
              <li>
                  <%= link_to 'Write New Post', new_post_path(), type: "button", class: "btn btn-primary btn-lg" %>
                </li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                  <li><%= link_to 'Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>

              <% else %>
                  <li><%= link_to 'Sign Up', "#sign_up", "data-toggle" => "modal" %></li>
                  <li><%= link_to 'Login', "#login", "data-toggle" => "modal" %> </li>
              <% end %>   
            </ul>
          </div>
        </div>
      </nav>
  </nav>

  <!-- Header Section -->
  <header>
    <div class="page-header">
      <%=image_tag("japan-banner2.jpg", class: "banner-image")%>
  </div>
  </header>

<%= yield %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <!--script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-CClVVnN2RnG6ICiyr-Vh_qLgQpbYhU0&libraries=places"></script-->



</body>
</html>